

services:
  phoenix:
    image: arizephoenix/phoenix:latest   
    container_name: phoenix
    ports:
      - "6006:6006"
    env_file:
      - .env
  server:
    build:
      context: .
    image: langserve_launch_example:latest
    container_name: langserve_launch_example
    ports:
      - "8001:8001"
    env_file:
      - .env
