name: CI

on:
  push:
    branches: [ "main", "feat/**" ]   # prend aussi les branches feat/…
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: "sk-test-dummy"          # clé factice
      PHOENIX_COLLECTOR_ENDPOINT: http://localhost:6006   # endpoint par défaut
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install -e app
          # ↳ compléments pour le test Phoenix
          pip install pytest \
                      opentelemetry-sdk>=1.32.1 \
                      arize-phoenix>=8.31.0 \
                      openinference-instrumentation-crewai>=0.1.28

      - name: Run tests
        run: pytest -q