name: CI

on:
  push:
    branches: [ "main", "feat/**" ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: "sk-test-dummy"
      PHOENIX_COLLECTOR_ENDPOINT: http://localhost:6006
      PYTHONPATH: ${{ github.workspace }}           # ← ajoute la racine au path
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install project + deps
        run: |
          python -m pip install --upgrade pip
          # 1) dépendances listées dans app/requirements.txt
          pip install -r app/requirements.txt
          # 2) CrewAI & compléments éventuels
          pip install crewai openinference-instrumentation-crewai arize-phoenix opentelemetry-sdk pytest
          # 3) installe ton code en editable afin que `import app...` fonctionne
          pip install -e .

      - name: Clean chroma artefacts
        run: rm -rf app/data/chroma || true  

      - name: Run tests
        run: pytest -q